/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Einführung',
      items: ['Einfuehrung', 'ersteSchritteMitUltraschall'],
    },
    {
      type: 'category',
      label: 'Übersicht',
      items: ['GUI-Gesamtuebersicht', 'anpassung'],
    },

    {
      type: 'category',
      label: 'Grundfunktionen',
      items: ['aufnahme', 'schnitt', 'postProduktion', 'export'],
    },
    {
      type: 'category',
      label: 'Fortgeschrittene',
      items: ['Aufnahme-fuer-Fortgeschrittene'],
    },
    {
      type: 'doc',
      id: 'glossar', // document ID
      label: 'Glossar', // sidebar label
    },
    {
      type: 'doc',
      id: 'ueber', // document ID
      label: 'Über', // sidebar label
    },
  ],

   
};
